### PR TITLE
Add fetch repo list utility

### PR DESCRIPTION
**Pull request by hmontero1205**
This is a lot more convenient than using the REST API yourself!

### CODE REVIEW

**Review by j-hui — CHANGES_REQUESTED** [review]
This is just personal preference, but can you have it dump the list to stdout rather than to a file? You could always easily redirect stdout to a file, more easily than specifying a file that is mapped to stdout.

**Comment by hmontero1205** [comment]
Understandable

**Review by j-hui — APPROVED** [review]
Approval

**Comment by j-hui** [comment]
(j-hui approved these changes)

**Pull request merged**
